dmnmodels = [['BMILevel'], ['datetest'], ['dinnerDecisions'], ['DogLicense'], ['InsuranceClaim'], ['multiplelayers'],
             ["onedtonerule"], ["ski guide"], ["testdmn"], ["simple"], ['sixdec'], ['deploycheck']]
model = ""
buttonstext = ""
deployname = ""
key = ""
name = ""
subdecvar = 0
counter = 0
myList = []
mylabels = []
notmyList = []
input = []
decisionkey = []
decisionname = []
output = []
oilist = []
inputbuttons = []
varinput = []
lst =[]
Globaltotal = []
a = 0
q = 0
w = -1
d = {}
jsoninput = {}
typedict = {"integer": int, "string": str, "boolean": bool, "long": int, "double": float, "date": str}
