myList = []
input = []
decisionkey = []
output = []
oilist = []
inputbuttons = []
varinput = []
a = 0
q = 0
d = {}
jsoninput = {}
typedict = {"integer": int, "string": str, "boolean": bool, "long": int, "double": float, "date": str}
